name: WakaTime Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Personalização de Layout e Componentes
          SHOW_SHORT_INFO: true
          SHOW_LOC_CHART: false
          SHOW_PROFILE_VIEWS: false
          SYMBOL_VERSION: 1
          
          # Estilização Visual
          BAR_STYLE: "solid"
          BAR_COLOR: "#38bdf8"
          BAR_TRACK_COLOR: "#1e293b"
          TEXT_PRIMARY_COLOR: "#f8fafc"
          TEXT_SECONDARY_COLOR: "#94a3b8"
